### ISSUE TITLE
Floating point exception error (core dumped) running super5

### ISSUE THREAD

**Issue by dnolin13** [rcedgar/muscle#40] opened 2022-08-09 21:17 UTC
Hello,
I am trying to align my protein sequences and it runs well for a while but then it throws this error:

Floating point exception (core dumped)
Floating point exception (core dumped)
Floating point exception (core dumped)
etc.

Does anyone know why/what this means? Thanks!

**Comment by rcedgar** [comment] 2022-08-09 21:53
That's strange, haven't seen that before, looks like a bug. If you post the sequences somewhere I can download I'll take a look. Please try to reduce the input data size first -- try splitting in two, see if one (or the other) half fails, repeat.

**Comment by rcedgar** [comment] 2022-09-15 23:35
Closing due to lack of test data required to reproduce the problem.

**Comment by rcedgar** [comment] 2023-07-31 13:36
I don't have test data to reproduce this. If you post your sequences somewhere I can download I'll take a look. Please try to reduce the input data size first -- try splitting in two, see if one (or the other) half fails, repeat.

**Comment by Lsz-20** [comment] 2023-07-31 13:40
> I don't have test data to reproduce this. If you post your sequences somewhere I can download I'll take a look. Please try to reduce the input data size first -- try splitting in two, see if one (or the other) half fails, repeat.

My data doesn't seem to support me for splitting

**Comment by rcedgar** [comment] 2023-07-31 13:42
ok, so at a guess the data is too big, what is the FASTA size in Mb & the longest sequence length?

**Comment by rcedgar** [comment] 2023-08-26 17:08
closed due to inactivity

**Closed by rcedgar** 2023-08-26 17:08 UTC
